spring:
  kafka:
    bootstrap-servers: 120.79.237.138:9092
    consumer:
      auto-offset-reset: earliest
      group-id: console-consumer-53989
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  rabbitmq:
      host: 120.79.237.138
      port: 5672
      username: guest
      password: guest